apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service
    service: book-service
spec:
  type: ClusterIP
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
